# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "snapatac2_fragments2h5ad"
description: "Create AnnData files from fragments.tsv.gz using SnapATAC2."
keywords:
  - snapatac2
  - fragments
  - h5ad
tools:
  - "snapatac2":
      description: "SnapATAC2: Single-cell epigenomics analysis toolkit."
      homepage: "https://kzhang.org/SnapATAC2"
      documentation: "https://kzhang.org/SnapATAC2"
      tool_dev_url: "https://github.com/kaizhang/SnapATAC2"
      licence: ["MIT"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - cellranger:
        type: directory
        description: Cell Ranger ARC output directory for one sample.
output:
  h5ad:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.h5ad":
          type: file
          description: AnnData object generated from fragments.
          pattern: "*.h5ad"
  versions_snapatac2:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "snapatac2":
          type: string
          description: The name of the tool
      - "python -c 'import snapatac2; print(snapatac2.__version__)'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@claptar"
maintainers:
  - "@claptar"
