# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "snapatac2_metrics"
description: "Compute fragment-level metrics on AnnData files with SnapATAC2."
keywords:
  - snapatac2
  - metrics
  - atac
tools:
  - "snapatac2":
      description: "SnapATAC2: Single-cell epigenomics analysis toolkit."
      homepage: "https://kzhang.org/SnapATAC2"
      documentation: "https://kzhang.org/SnapATAC2"
      tool_dev_url: "https://github.com/kaizhang/SnapATAC2"
      licence: ["MIT"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - h5ad:
        type: file
        description: Input AnnData object.
        pattern: "*.h5ad"
output:
  h5ad:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*_metrics.h5ad":
          type: file
          description: AnnData with computed metrics.
          pattern: "*.h5ad"
  versions_snapatac2:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "snapatac2":
          type: string
          description: The name of the tool
      - "python -c 'import snapatac2; print(snapatac2.__version__)'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@claptar"
maintainers:
  - "@claptar"
